version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/form
    versions:
    - 5.2.1
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/web-server-bundle
    versions:
    - 4.4.18
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/web-link
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/asset
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/expression-language
    versions:
    - 5.2.2
    - 5.2.3
